export interface PhraseLexiconEntry {
  phrase: string;
  concepts: string[];
}

export const PHRASE_LEXICON: PhraseLexiconEntry[] = [
  { phrase: 'stainless steel', concepts: ['STAINLESS'] },
  { phrase: 'нержавеющей стали', concepts: ['STAINLESS'] },
  { phrase: 'нержавеющая сталь', concepts: ['STAINLESS'] },
  { phrase: 'mild steel', concepts: ['MILD_STEEL'] },
  { phrase: 'carbon steel', concepts: ['MILD_STEEL'] },
  { phrase: 'черная сталь', concepts: ['MILD_STEEL'] },
  { phrase: 'чёрная сталь', concepts: ['MILD_STEEL'] },
  { phrase: 'linear guide', concepts: ['LINEAR_GUIDE'] },
  { phrase: 'линейная направляющая', concepts: ['LINEAR_GUIDE'] },
  { phrase: 'ball screw', concepts: ['BALL_SCREW'] },
  { phrase: 'шариковый винт', concepts: ['BALL_SCREW'] },
  { phrase: 'motor power', concepts: ['MOTOR', 'POWER'] },
  { phrase: 'мощность двигателя', concepts: ['MOTOR', 'POWER'] },
  { phrase: 'average working power', concepts: ['AVERAGE', 'WORKING', 'POWER'] },
  { phrase: 'feeding speed', concepts: ['FEED', 'SPEED'] },
  { phrase: 'скорость подачи', concepts: ['FEED', 'SPEED'] },
  { phrase: 'bending angle', concepts: ['BEND', 'ANGLE'] },
  { phrase: 'угол гибки', concepts: ['BEND', 'ANGLE'] },
  { phrase: 'bending thickness', concepts: ['BEND', 'THICKNESS'] },
  { phrase: 'feeding structure', concepts: ['FEED', 'STRUCTURE'] },
  { phrase: 'worktable structure', concepts: ['STRUCTURE'] },
  { phrase: 'system control unit', concepts: ['SYSTEM', 'CONTROL'] },
  { phrase: 'servo unit', concepts: ['SERVO'] },
  { phrase: 'dimension length', concepts: ['LENGTH'] },
  { phrase: 'dimension width', concepts: ['WIDTH'] },
  { phrase: 'dimension height', concepts: ['HEIGHT'] },
  { phrase: 'max feeding speed', concepts: ['MAX', 'FEED', 'SPEED'] },
  { phrase: 'max. feeding speed', concepts: ['MAX', 'FEED', 'SPEED'] },
  { phrase: 'bending thickness ss', concepts: ['BEND', 'THICKNESS', 'STAINLESS'] },
  { phrase: 'bending thickness ms', concepts: ['BEND', 'THICKNESS', 'MILD_STEEL'] },
  { phrase: 'bending thickness al', concepts: ['BEND', 'THICKNESS', 'ALUMINUM'] },
  { phrase: 'толщина нержавеющей стали', concepts: ['THICKNESS', 'STAINLESS'] },
  { phrase: 'толщина металла (алюминий)', concepts: ['THICKNESS', 'ALUMINUM'] },
  { phrase: 'потребляемая мощность', concepts: ['CONSUMPTION', 'POWER'] },
  { phrase: 'work table', concepts: ['WORKTABLE'] },
  { phrase: 'worktable', concepts: ['WORKTABLE'] },
  { phrase: 'рабочий стол', concepts: ['WORKTABLE'] },
  { phrase: 'рабочего стола', concepts: ['WORKTABLE'] },
  { phrase: 'linear guides', concepts: ['LINEAR_GUIDE'] },
  { phrase: 'линейные направляющие', concepts: ['LINEAR_GUIDE'] },
  { phrase: 'ballscrew', concepts: ['BALL_SCREW'] },
  { phrase: 'швп', concepts: ['BALL_SCREW'] },
  { phrase: 'сервопривод', concepts: ['SERVO'] },
  { phrase: 'углеродистая сталь', concepts: ['MILD_STEEL'] },
  { phrase: 'нержавейка', concepts: ['STAINLESS'] },
].sort((left, right) => right.phrase.length - left.phrase.length);

export const TOKEN_LEXICON: Record<string, string> = {
  motor: 'MOTOR',
  двигатель: 'MOTOR',
  двигателя: 'MOTOR',
  power: 'POWER',
  мощность: 'POWER',
  мощности: 'POWER',
  weight: 'WEIGHT',
  mass: 'WEIGHT',
  вес: 'WEIGHT',
  масса: 'WEIGHT',
  length: 'LENGTH',
  длина: 'LENGTH',
  width: 'WIDTH',
  ширина: 'WIDTH',
  height: 'HEIGHT',
  высота: 'HEIGHT',
  max: 'MAX',
  maximum: 'MAX',
  максимальная: 'MAX',
  максимальный: 'MAX',
  макс: 'MAX',
  min: 'MIN',
  minimum: 'MIN',
  минимальная: 'MIN',
  минимальный: 'MIN',
  мин: 'MIN',
  feeding: 'FEED',
  feed: 'FEED',
  подача: 'FEED',
  подачи: 'FEED',
  bending: 'BEND',
  bend: 'BEND',
  гибка: 'BEND',
  гибки: 'BEND',
  изгиб: 'BEND',
  изгиба: 'BEND',
  speed: 'SPEED',
  скорость: 'SPEED',
  angle: 'ANGLE',
  угол: 'ANGLE',
  thickness: 'THICKNESS',
  толщина: 'THICKNESS',
  material: 'MATERIAL',
  материал: 'MATERIAL',
  metal: 'MATERIAL',
  металл: 'MATERIAL',
  stainless: 'STAINLESS',
  ss: 'STAINLESS',
  aluminum: 'ALUMINUM',
  aluminium: 'ALUMINUM',
  al: 'ALUMINUM',
  алюминий: 'ALUMINUM',
  алюминия: 'ALUMINUM',
  ms: 'MILD_STEEL',
  accuracy: 'ACCURACY',
  точность: 'ACCURACY',
  average: 'AVERAGE',
  avg: 'AVERAGE',
  средняя: 'AVERAGE',
  средний: 'AVERAGE',
  working: 'WORKING',
  work: 'WORKING',
  рабочая: 'WORKING',
  рабочий: 'WORKING',
  consumption: 'CONSUMPTION',
  consumed: 'CONSUMPTION',
  потребляемая: 'CONSUMPTION',
  потребление: 'CONSUMPTION',
  dimension: 'DIMENSION',
  dimensions: 'DIMENSION',
  габарит: 'DIMENSION',
  габариты: 'DIMENSION',
  structure: 'STRUCTURE',
  конструкция: 'STRUCTURE',
  структура: 'STRUCTURE',
  control: 'CONTROL',
  управление: 'CONTROL',
  управления: 'CONTROL',
  system: 'SYSTEM',
  система: 'SYSTEM',
  servo: 'SERVO',
  серво: 'SERVO',
  bearing: 'BEARING',
  подшипник: 'BEARING',
  reducer: 'REDUCER',
  редуктор: 'REDUCER',
  tooling: 'STRUCTURE',
  unit: 'SYSTEM',
  components: 'SYSTEM',
  electrical: 'SYSTEM',
  pressing: 'STRUCTURE',
  arm: 'STRUCTURE',
  brush: 'STRUCTURE',
  roller: 'STRUCTURE',
  ball: 'STRUCTURE',
  table: 'STRUCTURE',
  worktable: 'WORKTABLE',
  нержавейка: 'STAINLESS',
  швп: 'BALL_SCREW',
  сервопривод: 'SERVO',
  блок: 'UNIT',
  направляющая: 'LINEAR_GUIDE',
  направляющие: 'LINEAR_GUIDE',
  винт: 'BALL_SCREW',
  углеродистая: 'MILD_STEEL',
  углеродистой: 'MILD_STEEL',
  нержавеющая: 'STAINLESS',
  черной: 'MILD_STEEL',
  чёрной: 'MILD_STEEL',
};

export const STOPWORDS = new Set([
  'of',
  'the',
  'for',
  'and',
  'a',
  'an',
  'to',
  'in',
  'on',
  'with',
  'по',
  'для',
  'и',
  'в',
  'на',
  'из',
  'от',
]);
